version: "3.8"

services:
    redis:
        image: redis:7
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
        restart: always

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672" # 관리 UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        restart: always

    registry:
        build:
            context: .
            dockerfile: registry/Dockerfile
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - LOG_LEVEL=DEBUG
        volumes:
            - ./registry:/app/registry
            - ./common:/app/common
        restart: always
        depends_on:
            - redis

    orchestrator:
        build:
            context: .
            dockerfile: orchestrator/Dockerfile
        ports:
            - "8001:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REGISTRY_URL=http://registry:8000
            - BROKER_URL=http://broker:8000
        volumes:
            - ./orchestrator:/app/orchestrator
            - ./common:/app/common
        restart: always
        depends_on:
            - registry

    broker:
        build:
            context: .
            dockerfile: ./broker/Dockerfile
        ports:
            - "8002:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - REGISTRY_URL=http://registry:8000
        depends_on:
            - redis
            - rabbitmq
            - registry
        restart: always

    agent_web_search:
        build:
            context: .
            dockerfile: ./agents/web_search/Dockerfile
        environment:
            - REGISTRY_URL=http://registry:8000
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
        depends_on:
            - registry
            - rabbitmq
        restart: always

    agent_writer:
        build:
            context: .
            dockerfile: ./agents/writer/Dockerfile
        environment:
            - REGISTRY_URL=http://registry:8000
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
        depends_on:
            - registry
            - rabbitmq
        restart: always

volumes:
    redis_data:
    rabbitmq_data:
