version: "3.8"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - multiagent-network

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672" # 관리 UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - multiagent-network

    registry:
        build:
            context: .
            dockerfile: Dockerfile.registry
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - AGENT_TTL=15
            - OPENAPI_TITLE=Agent Registry API
            - OPENAPI_DESCRIPTION=에이전트 등록 및 관리를 위한 API 서비스
            - OPENAPI_VERSION=1.0.0
        volumes:
            - ./registry:/app/registry
            - ./common:/app/common
        restart: always
        depends_on:
            redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - multiagent-network

    orchestrator:
        build:
            context: .
            dockerfile: orchestrator/Dockerfile
        ports:
            - "8001:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REGISTRY_URL=http://registry:8000
            - BROKER_URL=http://broker:8000
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

        volumes:
            - ./orchestrator:/app/orchestrator
            - ./common:/app/common
        restart: always
        depends_on:
            - registry
        networks:
            - multiagent-network

    broker:
        build:
            context: .
            dockerfile: ./broker/Dockerfile
        ports:
            - "8002:8000"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - REGISTRY_URL=http://registry:8000
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
        depends_on:
            - redis
            - rabbitmq
            - registry
        restart: always
        networks:
            - multiagent-network

    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173"
        environment:
            - VITE_API_BASE_URL=/
            - VITE_REGISTRY_URL=http://localhost:8000
            - VITE_ORCHESTRATOR_URL=http://localhost:8001
            - VITE_BROKER_URL=http://localhost:8002
        volumes:
            - ./ui:/app
            - /app/node_modules
        command: npm run dev -- --host 0.0.0.0
        depends_on:
            - orchestrator
            - registry
            - broker
        restart: always
        networks:
            - multiagent-network

volumes:
    redis-data:
    rabbitmq_data:

networks:
    multiagent-network:
        name: multiagent-network
